/** Safety Audit Report PDF builder using pdf-lib */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { AuditFinding } from './audit-processing';

const PAGE_WIDTH = 612; // US Letter
const PAGE_HEIGHT = 792;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 14;
const SECTION_GAP = 20;

const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.4, 0.4, 0.4);
const LIGHT_GRAY = rgb(0.7, 0.7, 0.7);
const ACCENT = rgb(0.29, 0.48, 0.96);
const RED = rgb(0.87, 0.24, 0.24);
const AMBER = rgb(0.85, 0.55, 0.1);
const GREEN = rgb(0.1, 0.65, 0.35);
const RED_BG = rgb(0.97, 0.92, 0.92);
const AMBER_BG = rgb(0.98, 0.95, 0.88);
const INFO_BG = rgb(0.92, 0.95, 0.98);

interface AuditReportOptions {
	projectName: string;
	companyName: string;
	date: string;
	summary: string;
	overallSeverity: string;
	findings: AuditFinding[];
	findingCount: number;
	criticalCount: number;
	warningCount: number;
	photo?: {
		imageBytes: ArrayBuffer;
		mimeType: string;
		filename: string;
	};
}

/** Wrap text into lines that fit within maxWidth */
function wrapText(
	text: string,
	font: any,
	fontSize: number,
	maxWidth: number
): string[] {
	const lines: string[] = [];
	const paragraphs = text.split('\n');

	for (const paragraph of paragraphs) {
		if (paragraph.trim() === '') {
			lines.push('');
			continue;
		}

		const words = paragraph.split(/\s+/);
		let currentLine = '';

		for (const word of words) {
			const testLine = currentLine ? `${currentLine} ${word}` : word;
			const width = font.widthOfTextAtSize(testLine, fontSize);

			if (width > maxWidth && currentLine) {
				lines.push(currentLine);
				currentLine = word;
			} else {
				currentLine = testLine;
			}
		}

		if (currentLine) {
			lines.push(currentLine);
		}
	}

	return lines;
}

export async function buildAuditReport(options: AuditReportOptions): Promise<Uint8Array> {
	const pdfDoc = await PDFDocument.create();
	const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
	const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
	const fontItalic = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

	let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
	let y = PAGE_HEIGHT - MARGIN;
	let pageNum = 1;

	function ensureSpace(needed: number) {
		if (y - needed < MARGIN + 30) {
			drawPageFooter(page, pageNum);
			page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
			y = PAGE_HEIGHT - MARGIN;
			pageNum++;
		}
	}

	function drawPageFooter(pg: any, num: number) {
		const text = `Page ${num}`;
		const width = fontRegular.widthOfTextAtSize(text, 8);
		pg.drawText(text, {
			x: PAGE_WIDTH / 2 - width / 2,
			y: 25,
			size: 8,
			font: fontRegular,
			color: LIGHT_GRAY,
		});
		const footer = 'Generated by CollectRelay';
		const fWidth = fontRegular.widthOfTextAtSize(footer, 7);
		pg.drawText(footer, {
			x: PAGE_WIDTH - MARGIN - fWidth,
			y: 25,
			size: 7,
			font: fontRegular,
			color: LIGHT_GRAY,
		});
	}

	function drawHR() {
		page.drawLine({
			start: { x: MARGIN, y },
			end: { x: PAGE_WIDTH - MARGIN, y },
			thickness: 0.5,
			color: LIGHT_GRAY,
		});
	}

	function severityColor(severity: string) {
		if (severity === 'critical') return RED;
		if (severity === 'warning') return AMBER;
		return ACCENT;
	}

	function severityBg(severity: string) {
		if (severity === 'critical') return RED_BG;
		if (severity === 'warning') return AMBER_BG;
		return INFO_BG;
	}

	function overallColor(severity: string) {
		if (severity === 'critical') return RED;
		if (severity === 'warning') return AMBER;
		return GREEN;
	}

	// ── COVER PAGE ──────────────────────────────────────

	// Company name (right-aligned)
	const companyWidth = fontBold.widthOfTextAtSize(options.companyName, 14);
	page.drawText(options.companyName, {
		x: PAGE_WIDTH - MARGIN - companyWidth,
		y: y - 14,
		size: 14,
		font: fontBold,
		color: BLACK,
	});

	// Date (right-aligned)
	const dateWidth = fontRegular.widthOfTextAtSize(options.date, 9);
	page.drawText(options.date, {
		x: PAGE_WIDTH - MARGIN - dateWidth,
		y: y - 28,
		size: 9,
		font: fontRegular,
		color: GRAY,
	});

	y -= 50 + SECTION_GAP;
	drawHR();
	y -= SECTION_GAP;

	// Title
	const title = 'Site Safety Audit Report';
	const tw = fontBold.widthOfTextAtSize(title, 22);
	page.drawText(title, {
		x: PAGE_WIDTH / 2 - tw / 2,
		y,
		size: 22,
		font: fontBold,
		color: ACCENT,
	});
	y -= 30;

	drawHR();
	y -= SECTION_GAP;

	// Overall severity badge
	const sevLabel = options.overallSeverity.toUpperCase();
	const sevColor = overallColor(options.overallSeverity);
	const sevWidth = fontBold.widthOfTextAtSize(sevLabel, 16);

	page.drawRectangle({
		x: PAGE_WIDTH / 2 - (sevWidth + 30) / 2,
		y: y - 6,
		width: sevWidth + 30,
		height: 28,
		color: sevColor,
		borderColor: sevColor,
		borderWidth: 0,
	});
	page.drawText(sevLabel, {
		x: PAGE_WIDTH / 2 - sevWidth / 2,
		y: y,
		size: 16,
		font: fontBold,
		color: rgb(1, 1, 1),
	});
	y -= 40;

	// Project
	page.drawText('Project:', {
		x: MARGIN,
		y,
		size: 10,
		font: fontBold,
		color: GRAY,
	});
	page.drawText(options.projectName, {
		x: MARGIN + 55,
		y,
		size: 10,
		font: fontRegular,
		color: BLACK,
	});
	y -= LINE_HEIGHT;

	// Finding counts
	page.drawText('Findings:', {
		x: MARGIN,
		y,
		size: 10,
		font: fontBold,
		color: GRAY,
	});

	let countX = MARGIN + 55;
	if (options.criticalCount > 0) {
		const ct = `${options.criticalCount} Critical`;
		page.drawText(ct, { x: countX, y, size: 10, font: fontBold, color: RED });
		countX += fontBold.widthOfTextAtSize(ct, 10) + 15;
	}
	if (options.warningCount > 0) {
		const wt = `${options.warningCount} Warning`;
		page.drawText(wt, { x: countX, y, size: 10, font: fontBold, color: AMBER });
		countX += fontBold.widthOfTextAtSize(wt, 10) + 15;
	}
	const infoCount = options.findingCount - options.criticalCount - options.warningCount;
	if (infoCount > 0) {
		const it = `${infoCount} Info`;
		page.drawText(it, { x: countX, y, size: 10, font: fontBold, color: ACCENT });
	}
	if (options.findingCount === 0) {
		page.drawText('No issues found', { x: countX, y, size: 10, font: fontRegular, color: GREEN });
	}
	y -= LINE_HEIGHT * 2;

	// Summary
	if (options.summary) {
		page.drawText('Summary:', {
			x: MARGIN,
			y,
			size: 10,
			font: fontBold,
			color: GRAY,
		});
		y -= LINE_HEIGHT;

		const summaryLines = wrapText(options.summary, fontRegular, 10, CONTENT_WIDTH);
		for (const line of summaryLines) {
			if (line === '') { y -= LINE_HEIGHT * 0.6; continue; }
			page.drawText(line, { x: MARGIN, y, size: 10, font: fontRegular, color: BLACK });
			y -= LINE_HEIGHT;
		}
	}

	drawPageFooter(page, pageNum);

	// ── FINDINGS PAGES ──────────────────────────────────────

	if (options.findings.length > 0) {
		page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
		y = PAGE_HEIGHT - MARGIN;
		pageNum++;

		page.drawText('Detailed Findings', {
			x: MARGIN,
			y,
			size: 16,
			font: fontBold,
			color: BLACK,
		});
		y -= 10;
		drawHR();
		y -= SECTION_GAP;

		for (let i = 0; i < options.findings.length; i++) {
			const finding = options.findings[i];
			const findingHeight = 100; // estimate
			ensureSpace(findingHeight);

			// Severity color bar on left
			const barColor = severityColor(finding.severity);
			const bgColor = severityBg(finding.severity);

			// Background rectangle
			const descLines = wrapText(finding.description, fontRegular, 9, CONTENT_WIDTH - 20);
			const recLines = wrapText(finding.recommendation, fontRegular, 9, CONTENT_WIDTH - 20);
			const blockHeight = 32 + (descLines.length * 12) + 16 + (recLines.length * 12) + (finding.osha_reference ? 16 : 0) + 10;

			ensureSpace(blockHeight);

			page.drawRectangle({
				x: MARGIN,
				y: y - blockHeight + 14,
				width: CONTENT_WIDTH,
				height: blockHeight,
				color: bgColor,
			});

			// Left color bar
			page.drawRectangle({
				x: MARGIN,
				y: y - blockHeight + 14,
				width: 4,
				height: blockHeight,
				color: barColor,
			});

			// Finding header: code + severity + category
			const codeText = finding.code;
			page.drawText(codeText, {
				x: MARGIN + 12,
				y,
				size: 10,
				font: fontBold,
				color: barColor,
			});

			const sevBadge = finding.severity.toUpperCase();
			const catBadge = finding.category;
			const badges = `${sevBadge}  |  ${catBadge}`;
			const badgeWidth = fontRegular.widthOfTextAtSize(badges, 8);
			page.drawText(badges, {
				x: PAGE_WIDTH - MARGIN - badgeWidth - 8,
				y: y + 1,
				size: 8,
				font: fontBold,
				color: barColor,
			});

			y -= 16;

			// Description
			for (const line of descLines) {
				if (line === '') { y -= 8; continue; }
				page.drawText(line, {
					x: MARGIN + 12,
					y,
					size: 9,
					font: fontRegular,
					color: BLACK,
				});
				y -= 12;
			}
			y -= 4;

			// Recommendation
			page.drawText('Recommendation:', {
				x: MARGIN + 12,
				y,
				size: 8,
				font: fontBold,
				color: GRAY,
			});
			y -= 12;

			for (const line of recLines) {
				if (line === '') { y -= 8; continue; }
				page.drawText(line, {
					x: MARGIN + 12,
					y,
					size: 9,
					font: fontItalic,
					color: GRAY,
				});
				y -= 12;
			}

			// OSHA reference
			if (finding.osha_reference) {
				y -= 2;
				page.drawText(`Ref: ${finding.osha_reference}`, {
					x: MARGIN + 12,
					y,
					size: 8,
					font: fontRegular,
					color: ACCENT,
				});
				y -= 12;
			}

			y -= SECTION_GAP;
		}

		drawPageFooter(page, pageNum);
	}

	// ── PHOTO PAGE ──────────────────────────────────────

	if (options.photo) {
		page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
		y = PAGE_HEIGHT - MARGIN;
		pageNum++;

		page.drawText('Source Photo', {
			x: MARGIN,
			y,
			size: 14,
			font: fontBold,
			color: BLACK,
		});

		const fnWidth = fontRegular.widthOfTextAtSize(options.photo.filename, 9);
		page.drawText(options.photo.filename, {
			x: PAGE_WIDTH - MARGIN - fnWidth,
			y,
			size: 9,
			font: fontRegular,
			color: GRAY,
		});

		y -= 5;
		drawHR();
		y -= SECTION_GAP;

		try {
			let image;
			if (options.photo.mimeType.includes('png')) {
				image = await pdfDoc.embedPng(options.photo.imageBytes);
			} else {
				image = await pdfDoc.embedJpg(options.photo.imageBytes);
			}

			if (image) {
				const maxImgWidth = CONTENT_WIDTH;
				const maxImgHeight = 550;
				const scale = Math.min(maxImgWidth / image.width, maxImgHeight / image.height, 1);
				const drawWidth = image.width * scale;
				const drawHeight = image.height * scale;

				page.drawImage(image, {
					x: MARGIN + (CONTENT_WIDTH - drawWidth) / 2,
					y: y - drawHeight,
					width: drawWidth,
					height: drawHeight,
				});
			}
		} catch {
			page.drawText('[Image could not be embedded]', {
				x: MARGIN,
				y,
				size: 10,
				font: fontItalic,
				color: GRAY,
			});
		}

		drawPageFooter(page, pageNum);
	}

	return await pdfDoc.save();
}
