/** Daily Field Log PDF builder using pdf-lib */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const PAGE_WIDTH = 612; // US Letter
const PAGE_HEIGHT = 792;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 14;
const SECTION_GAP = 20;

const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.4, 0.4, 0.4);
const LIGHT_GRAY = rgb(0.7, 0.7, 0.7);
const ACCENT = rgb(0.29, 0.48, 0.96);
const RED = rgb(0.87, 0.24, 0.24);
const AMBER = rgb(0.85, 0.55, 0.1);
const GREEN = rgb(0.1, 0.65, 0.35);

interface VoiceNoteEntry {
	id: string;
	transcript: string | null;
	ai_actions: string | null;
	duration_seconds: number | null;
	created_at: string;
}

interface PhotoNoteEntry {
	id: string;
	title: string | null;
	notes: string | null;
	ai_description: string | null;
	ai_actions: string | null;
	imageBytes?: ArrayBuffer;
	mimeType?: string;
	created_at: string;
}

interface AuditEntry {
	id: string;
	summary: string | null;
	overall_severity: string | null;
	finding_count: number;
	critical_count: number;
	warning_count: number;
	created_at: string;
}

export interface DailyLogOptions {
	projectName: string;
	companyName: string;
	date: string;
	generatedAt: string;
	voiceNotes: VoiceNoteEntry[];
	photoNotes: PhotoNoteEntry[];
	siteAudits: AuditEntry[];
}

/** Wrap text into lines that fit within maxWidth */
function wrapText(
	text: string,
	font: any,
	fontSize: number,
	maxWidth: number
): string[] {
	const lines: string[] = [];
	const paragraphs = text.split('\n');

	for (const paragraph of paragraphs) {
		if (paragraph.trim() === '') {
			lines.push('');
			continue;
		}

		const words = paragraph.split(/\s+/);
		let currentLine = '';

		for (const word of words) {
			const testLine = currentLine ? `${currentLine} ${word}` : word;
			const width = font.widthOfTextAtSize(testLine, fontSize);

			if (width > maxWidth && currentLine) {
				lines.push(currentLine);
				currentLine = word;
			} else {
				currentLine = testLine;
			}
		}

		if (currentLine) {
			lines.push(currentLine);
		}
	}

	return lines;
}

function formatTime(dateStr: string): string {
	try {
		const d = new Date(dateStr + 'Z');
		return d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
	} catch {
		return '';
	}
}

function formatDuration(seconds: number | null): string {
	if (!seconds) return '';
	const m = Math.floor(seconds / 60);
	const s = seconds % 60;
	return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

function severityColor(severity: string | null) {
	if (severity === 'critical') return RED;
	if (severity === 'warning') return AMBER;
	return GREEN;
}

export async function buildDailyLogReport(options: DailyLogOptions): Promise<Uint8Array> {
	const pdfDoc = await PDFDocument.create();
	const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
	const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
	const fontItalic = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

	let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
	let y = PAGE_HEIGHT - MARGIN;
	let pageNum = 1;

	function ensureSpace(needed: number) {
		if (y - needed < MARGIN + 30) {
			drawPageFooter(page, pageNum);
			page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
			y = PAGE_HEIGHT - MARGIN;
			pageNum++;
		}
	}

	function drawPageFooter(pg: any, num: number) {
		const text = `Page ${num}`;
		const width = fontRegular.widthOfTextAtSize(text, 8);
		pg.drawText(text, {
			x: PAGE_WIDTH / 2 - width / 2,
			y: 25,
			size: 8,
			font: fontRegular,
			color: LIGHT_GRAY,
		});
		const footer = 'Generated by CollectRelay';
		const fWidth = fontRegular.widthOfTextAtSize(footer, 7);
		pg.drawText(footer, {
			x: PAGE_WIDTH - MARGIN - fWidth,
			y: 25,
			size: 7,
			font: fontRegular,
			color: LIGHT_GRAY,
		});
	}

	function drawHR() {
		page.drawLine({
			start: { x: MARGIN, y },
			end: { x: PAGE_WIDTH - MARGIN, y },
			thickness: 0.5,
			color: LIGHT_GRAY,
		});
	}

	function drawSectionHeader(title: string) {
		ensureSpace(50);
		y -= 5;
		drawHR();
		y -= SECTION_GAP;

		page.drawText(title, {
			x: MARGIN,
			y,
			size: 14,
			font: fontBold,
			color: ACCENT,
		});
		y -= 8;
		drawHR();
		y -= SECTION_GAP;
	}

	// ── COVER PAGE ──────────────────────────────────────

	// Company name (right-aligned)
	const companyWidth = fontBold.widthOfTextAtSize(options.companyName, 14);
	page.drawText(options.companyName, {
		x: PAGE_WIDTH - MARGIN - companyWidth,
		y: y - 14,
		size: 14,
		font: fontBold,
		color: BLACK,
	});

	// Date (right-aligned)
	const dateWidth = fontRegular.widthOfTextAtSize(options.date, 9);
	page.drawText(options.date, {
		x: PAGE_WIDTH - MARGIN - dateWidth,
		y: y - 28,
		size: 9,
		font: fontRegular,
		color: GRAY,
	});

	y -= 50 + SECTION_GAP;
	drawHR();
	y -= SECTION_GAP;

	// Title
	const title = 'Daily Field Log';
	const tw = fontBold.widthOfTextAtSize(title, 22);
	page.drawText(title, {
		x: PAGE_WIDTH / 2 - tw / 2,
		y,
		size: 22,
		font: fontBold,
		color: ACCENT,
	});
	y -= 30;

	drawHR();
	y -= SECTION_GAP;

	// Project name
	page.drawText('Project:', {
		x: MARGIN,
		y,
		size: 10,
		font: fontBold,
		color: GRAY,
	});
	page.drawText(options.projectName, {
		x: MARGIN + 55,
		y,
		size: 10,
		font: fontRegular,
		color: BLACK,
	});
	y -= LINE_HEIGHT;

	// Generated timestamp
	page.drawText('Generated:', {
		x: MARGIN,
		y,
		size: 10,
		font: fontBold,
		color: GRAY,
	});
	page.drawText(options.generatedAt, {
		x: MARGIN + 70,
		y,
		size: 10,
		font: fontRegular,
		color: BLACK,
	});
	y -= LINE_HEIGHT * 2;

	// Summary stats
	const stats: string[] = [];
	if (options.voiceNotes.length > 0) {
		stats.push(`${options.voiceNotes.length} Voice Note${options.voiceNotes.length !== 1 ? 's' : ''}`);
	}
	if (options.photoNotes.length > 0) {
		stats.push(`${options.photoNotes.length} Photo${options.photoNotes.length !== 1 ? 's' : ''}`);
	}
	if (options.siteAudits.length > 0) {
		stats.push(`${options.siteAudits.length} Safety Audit${options.siteAudits.length !== 1 ? 's' : ''}`);
	}

	if (stats.length > 0) {
		const statsText = stats.join('  •  ');
		const statsWidth = fontRegular.widthOfTextAtSize(statsText, 11);
		page.drawText(statsText, {
			x: PAGE_WIDTH / 2 - statsWidth / 2,
			y,
			size: 11,
			font: fontRegular,
			color: GRAY,
		});
		y -= LINE_HEIGHT * 2;
	}

	drawPageFooter(page, pageNum);

	// ── VOICE NOTES SECTION ──────────────────────────────────────

	if (options.voiceNotes.length > 0) {
		drawSectionHeader(`Voice Notes (${options.voiceNotes.length})`);

		for (let i = 0; i < options.voiceNotes.length; i++) {
			const vn = options.voiceNotes[i];
			ensureSpace(60);

			// Header line: "Voice Note #X" + time + duration
			const label = `Voice Note ${i + 1}`;
			page.drawText(label, {
				x: MARGIN,
				y,
				size: 10,
				font: fontBold,
				color: BLACK,
			});

			const meta: string[] = [];
			const time = formatTime(vn.created_at);
			if (time) meta.push(time);
			const dur = formatDuration(vn.duration_seconds);
			if (dur) meta.push(dur);
			if (meta.length > 0) {
				const metaText = meta.join('  •  ');
				const metaWidth = fontRegular.widthOfTextAtSize(metaText, 9);
				page.drawText(metaText, {
					x: PAGE_WIDTH - MARGIN - metaWidth,
					y,
					size: 9,
					font: fontRegular,
					color: GRAY,
				});
			}
			y -= LINE_HEIGHT + 2;

			// Transcript
			if (vn.transcript) {
				const transcriptLines = wrapText(vn.transcript, fontRegular, 9, CONTENT_WIDTH);
				for (const line of transcriptLines) {
					ensureSpace(LINE_HEIGHT);
					if (line === '') { y -= LINE_HEIGHT * 0.6; continue; }
					page.drawText(line, {
						x: MARGIN,
						y,
						size: 9,
						font: fontRegular,
						color: BLACK,
					});
					y -= LINE_HEIGHT - 2;
				}
				y -= 4;
			} else {
				page.drawText('[No transcript available]', {
					x: MARGIN,
					y,
					size: 9,
					font: fontItalic,
					color: LIGHT_GRAY,
				});
				y -= LINE_HEIGHT;
			}

			// AI-extracted actions
			if (vn.ai_actions) {
				try {
					const actions = JSON.parse(vn.ai_actions);
					if (Array.isArray(actions) && actions.length > 0) {
						ensureSpace(LINE_HEIGHT * 2);
						page.drawText('AI-Extracted Actions:', {
							x: MARGIN,
							y,
							size: 8,
							font: fontBold,
							color: ACCENT,
						});
						y -= LINE_HEIGHT;

						for (const action of actions) {
							ensureSpace(LINE_HEIGHT);
							const actionText = typeof action === 'string' ? action : (action.text || action.description || JSON.stringify(action));
							const bullet = `• ${actionText}`;
							const actionLines = wrapText(bullet, fontRegular, 9, CONTENT_WIDTH - 10);
							for (const line of actionLines) {
								ensureSpace(LINE_HEIGHT);
								page.drawText(line, {
									x: MARGIN + 5,
									y,
									size: 9,
									font: fontRegular,
									color: BLACK,
								});
								y -= LINE_HEIGHT - 2;
							}
						}
					}
				} catch { /* ignore parse errors */ }
			}

			y -= SECTION_GAP * 0.6;

			// Divider between notes
			if (i < options.voiceNotes.length - 1) {
				page.drawLine({
					start: { x: MARGIN + 20, y },
					end: { x: PAGE_WIDTH - MARGIN - 20, y },
					thickness: 0.3,
					color: LIGHT_GRAY,
				});
				y -= SECTION_GAP * 0.6;
			}
		}
	}

	// ── PHOTO NOTES SECTION ──────────────────────────────────────

	if (options.photoNotes.length > 0) {
		drawSectionHeader(`Photos (${options.photoNotes.length})`);

		for (let i = 0; i < options.photoNotes.length; i++) {
			const photo = options.photoNotes[i];

			// Start new page for each photo to give room for image
			if (i > 0) {
				drawPageFooter(page, pageNum);
				page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
				y = PAGE_HEIGHT - MARGIN;
				pageNum++;
			}

			// Header: "Photo X of Y" + time
			const label = `Photo ${i + 1} of ${options.photoNotes.length}`;
			page.drawText(label, {
				x: MARGIN,
				y,
				size: 9,
				font: fontRegular,
				color: GRAY,
			});

			const time = formatTime(photo.created_at);
			if (time) {
				const timeWidth = fontRegular.widthOfTextAtSize(time, 9);
				page.drawText(time, {
					x: PAGE_WIDTH - MARGIN - timeWidth,
					y,
					size: 9,
					font: fontRegular,
					color: GRAY,
				});
			}
			y -= 5;
			drawHR();
			y -= SECTION_GAP;

			// Title
			if (photo.title) {
				page.drawText(photo.title, {
					x: MARGIN,
					y,
					size: 14,
					font: fontBold,
					color: BLACK,
				});
				y -= 20;
			}

			// Embed the image
			if (photo.imageBytes && photo.mimeType) {
				try {
					let image;
					if (photo.mimeType.includes('png')) {
						image = await pdfDoc.embedPng(photo.imageBytes);
					} else {
						image = await pdfDoc.embedJpg(photo.imageBytes);
					}

					if (image) {
						const maxImgWidth = CONTENT_WIDTH;
						const maxImgHeight = 300;
						const scale = Math.min(maxImgWidth / image.width, maxImgHeight / image.height, 1);
						const drawWidth = image.width * scale;
						const drawHeight = image.height * scale;

						if (y - drawHeight >= MARGIN + 100) {
							page.drawImage(image, {
								x: MARGIN + (CONTENT_WIDTH - drawWidth) / 2,
								y: y - drawHeight,
								width: drawWidth,
								height: drawHeight,
							});
							y -= drawHeight + 15;
						} else {
							// Scale down to fit
							const availableHeight = y - MARGIN - 150;
							if (availableHeight > 80) {
								const fitScale = Math.min(scale, availableHeight / image.height);
								const fitWidth = image.width * fitScale;
								const fitHeight = image.height * fitScale;

								page.drawImage(image, {
									x: MARGIN + (CONTENT_WIDTH - fitWidth) / 2,
									y: y - fitHeight,
									width: fitWidth,
									height: fitHeight,
								});
								y -= fitHeight + 15;
							}
						}
					}
				} catch {
					page.drawText('[Image could not be embedded]', {
						x: MARGIN,
						y,
						size: 10,
						font: fontItalic,
						color: GRAY,
					});
					y -= LINE_HEIGHT;
				}
			}

			// Notes
			if (photo.notes) {
				ensureSpace(LINE_HEIGHT * 3);
				page.drawText('Notes:', {
					x: MARGIN,
					y,
					size: 9,
					font: fontBold,
					color: GRAY,
				});
				y -= LINE_HEIGHT;

				const noteLines = wrapText(photo.notes, fontRegular, 10, CONTENT_WIDTH);
				for (const line of noteLines) {
					ensureSpace(LINE_HEIGHT);
					if (line === '') { y -= LINE_HEIGHT * 0.6; continue; }
					page.drawText(line, {
						x: MARGIN,
						y,
						size: 10,
						font: fontRegular,
						color: BLACK,
					});
					y -= LINE_HEIGHT;
				}
				y -= 5;
			}

			// AI Description
			if (photo.ai_description) {
				ensureSpace(LINE_HEIGHT * 3);
				page.drawText('AI Analysis:', {
					x: MARGIN,
					y,
					size: 9,
					font: fontBold,
					color: ACCENT,
				});
				y -= LINE_HEIGHT;

				const descLines = wrapText(photo.ai_description, fontItalic, 9, CONTENT_WIDTH);
				for (const line of descLines) {
					ensureSpace(LINE_HEIGHT);
					if (line === '') { y -= LINE_HEIGHT * 0.6; continue; }
					page.drawText(line, {
						x: MARGIN,
						y,
						size: 9,
						font: fontItalic,
						color: GRAY,
					});
					y -= LINE_HEIGHT - 2;
				}
			}

			drawPageFooter(page, pageNum);
		}
	}

	// ── SAFETY AUDITS SECTION ──────────────────────────────────────

	if (options.siteAudits.length > 0) {
		drawSectionHeader(`Safety Audits (${options.siteAudits.length})`);

		for (let i = 0; i < options.siteAudits.length; i++) {
			const audit = options.siteAudits[i];
			ensureSpace(80);

			// Header: "Audit #X" + time + severity badge
			const label = `Audit ${i + 1}`;
			page.drawText(label, {
				x: MARGIN,
				y,
				size: 10,
				font: fontBold,
				color: BLACK,
			});

			// Severity badge (right-aligned)
			if (audit.overall_severity) {
				const sevLabel = audit.overall_severity.toUpperCase();
				const sevColor = severityColor(audit.overall_severity);
				const sevWidth = fontBold.widthOfTextAtSize(sevLabel, 8);

				page.drawRectangle({
					x: PAGE_WIDTH - MARGIN - sevWidth - 12,
					y: y - 4,
					width: sevWidth + 12,
					height: 16,
					color: sevColor,
				});
				page.drawText(sevLabel, {
					x: PAGE_WIDTH - MARGIN - sevWidth - 6,
					y: y - 1,
					size: 8,
					font: fontBold,
					color: rgb(1, 1, 1),
				});
			}

			const time = formatTime(audit.created_at);
			if (time) {
				const offset = audit.overall_severity ? 80 : 0;
				const timeWidth = fontRegular.widthOfTextAtSize(time, 9);
				page.drawText(time, {
					x: PAGE_WIDTH - MARGIN - timeWidth - offset,
					y,
					size: 9,
					font: fontRegular,
					color: GRAY,
				});
			}
			y -= LINE_HEIGHT + 2;

			// Finding counts
			let countX = MARGIN;
			const counts: string[] = [];
			if (audit.critical_count > 0) counts.push(`${audit.critical_count} Critical`);
			if (audit.warning_count > 0) counts.push(`${audit.warning_count} Warning`);
			const infoCount = audit.finding_count - audit.critical_count - audit.warning_count;
			if (infoCount > 0) counts.push(`${infoCount} Info`);

			if (counts.length > 0) {
				const countsText = `Findings: ${counts.join(', ')}`;
				page.drawText(countsText, {
					x: countX,
					y,
					size: 9,
					font: fontRegular,
					color: GRAY,
				});
				y -= LINE_HEIGHT;
			} else if (audit.finding_count === 0) {
				page.drawText('No issues found', {
					x: countX,
					y,
					size: 9,
					font: fontRegular,
					color: GREEN,
				});
				y -= LINE_HEIGHT;
			}

			// Summary
			if (audit.summary) {
				y -= 2;
				const summaryLines = wrapText(audit.summary, fontRegular, 9, CONTENT_WIDTH);
				for (const line of summaryLines) {
					ensureSpace(LINE_HEIGHT);
					if (line === '') { y -= LINE_HEIGHT * 0.6; continue; }
					page.drawText(line, {
						x: MARGIN,
						y,
						size: 9,
						font: fontRegular,
						color: BLACK,
					});
					y -= LINE_HEIGHT - 2;
				}
			}

			y -= SECTION_GAP * 0.6;

			// Divider between audits
			if (i < options.siteAudits.length - 1) {
				page.drawLine({
					start: { x: MARGIN + 20, y },
					end: { x: PAGE_WIDTH - MARGIN - 20, y },
					thickness: 0.3,
					color: LIGHT_GRAY,
				});
				y -= SECTION_GAP * 0.6;
			}
		}

		drawPageFooter(page, pageNum);
	}

	return await pdfDoc.save();
}
