/** PDF template builder using pdf-lib */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const PAGE_WIDTH = 612; // US Letter
const PAGE_HEIGHT = 792;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 14;
const SECTION_GAP = 20;

// Colors
const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.4, 0.4, 0.4);
const LIGHT_GRAY = rgb(0.7, 0.7, 0.7);
const ACCENT = rgb(0.29, 0.48, 0.96); // #4a7af5

interface BuildOptions {
	title: string;
	companyName: string;
	date: string;
	proFields: Record<string, string>;
	clientFields: Record<string, string>;
	bodyText: string;
	logoBytes?: ArrayBuffer | null;
	logoMimeType?: string;
}

/** Wrap text into lines that fit within maxWidth */
function wrapText(
	text: string,
	font: any,
	fontSize: number,
	maxWidth: number
): string[] {
	const lines: string[] = [];
	const paragraphs = text.split('\n');

	for (const paragraph of paragraphs) {
		if (paragraph.trim() === '') {
			lines.push('');
			continue;
		}

		const words = paragraph.split(/\s+/);
		let currentLine = '';

		for (const word of words) {
			const testLine = currentLine ? `${currentLine} ${word}` : word;
			const width = font.widthOfTextAtSize(testLine, fontSize);

			if (width > maxWidth && currentLine) {
				lines.push(currentLine);
				currentLine = word;
			} else {
				currentLine = testLine;
			}
		}

		if (currentLine) {
			lines.push(currentLine);
		}
	}

	return lines;
}

/** Draw a horizontal rule */
function drawHR(page: any, y: number) {
	page.drawLine({
		start: { x: MARGIN, y },
		end: { x: PAGE_WIDTH - MARGIN, y },
		thickness: 0.5,
		color: LIGHT_GRAY,
	});
}

export async function buildTemplatePdf(options: BuildOptions): Promise<Uint8Array> {
	const pdfDoc = await PDFDocument.create();
	const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
	const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

	let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
	let y = PAGE_HEIGHT - MARGIN;
	let pageNum = 1;

	/** Get a new page if we're running low on space */
	function ensureSpace(needed: number) {
		if (y - needed < MARGIN + 30) {
			// Draw page number on current page
			drawPageNumber(page, pageNum);
			page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
			y = PAGE_HEIGHT - MARGIN;
			pageNum++;
		}
	}

	function drawPageNumber(pg: any, num: number) {
		const text = `Page ${num}`;
		const width = fontRegular.widthOfTextAtSize(text, 8);
		pg.drawText(text, {
			x: PAGE_WIDTH / 2 - width / 2,
			y: 25,
			size: 8,
			font: fontRegular,
			color: LIGHT_GRAY,
		});
		// Footer watermark
		const footer = 'Generated by CollectRelay';
		const fWidth = fontRegular.widthOfTextAtSize(footer, 7);
		pg.drawText(footer, {
			x: PAGE_WIDTH - MARGIN - fWidth,
			y: 25,
			size: 7,
			font: fontRegular,
			color: LIGHT_GRAY,
		});
	}

	// ── HEADER ──────────────────────────────────────────
	let logoHeight = 0;
	if (options.logoBytes && options.logoMimeType) {
		try {
			let image;
			if (options.logoMimeType.includes('png')) {
				image = await pdfDoc.embedPng(options.logoBytes);
			} else if (options.logoMimeType.includes('jpeg') || options.logoMimeType.includes('jpg')) {
				image = await pdfDoc.embedJpg(options.logoBytes);
			}

			if (image) {
				const maxLogoHeight = 50;
				const maxLogoWidth = 150;
				const scale = Math.min(
					maxLogoWidth / image.width,
					maxLogoHeight / image.height,
					1
				);
				const drawWidth = image.width * scale;
				const drawHeight = image.height * scale;

				page.drawImage(image, {
					x: MARGIN,
					y: y - drawHeight,
					width: drawWidth,
					height: drawHeight,
				});
				logoHeight = drawHeight;
			}
		} catch {
			// Skip logo if format not supported
		}
	}

	// Company name (right-aligned)
	const companyWidth = fontBold.widthOfTextAtSize(options.companyName, 14);
	page.drawText(options.companyName, {
		x: PAGE_WIDTH - MARGIN - companyWidth,
		y: y - 14,
		size: 14,
		font: fontBold,
		color: BLACK,
	});

	// Date (right-aligned, below company)
	const dateWidth = fontRegular.widthOfTextAtSize(options.date, 9);
	page.drawText(options.date, {
		x: PAGE_WIDTH - MARGIN - dateWidth,
		y: y - 28,
		size: 9,
		font: fontRegular,
		color: GRAY,
	});

	y -= Math.max(logoHeight, 35) + SECTION_GAP;

	// ── TITLE ──────────────────────────────────────────
	drawHR(page, y);
	y -= SECTION_GAP;

	const titleWidth = fontBold.widthOfTextAtSize(options.title, 18);
	page.drawText(options.title, {
		x: PAGE_WIDTH / 2 - titleWidth / 2,
		y,
		size: 18,
		font: fontBold,
		color: ACCENT,
	});
	y -= SECTION_GAP + 5;

	drawHR(page, y);
	y -= SECTION_GAP;

	// ── PRO INFO ──────────────────────────────────────
	const proEntries = Object.entries(options.proFields).filter(([, v]) => v);
	if (proEntries.length > 0) {
		page.drawText('FROM:', {
			x: MARGIN,
			y,
			size: 8,
			font: fontBold,
			color: GRAY,
		});
		y -= LINE_HEIGHT;

		for (const [label, value] of proEntries) {
			ensureSpace(LINE_HEIGHT);
			page.drawText(`${label}: ${value}`, {
				x: MARGIN,
				y,
				size: 10,
				font: fontRegular,
				color: BLACK,
			});
			y -= LINE_HEIGHT;
		}
		y -= 5;
	}

	// ── CLIENT INFO ──────────────────────────────────
	const clientEntries = Object.entries(options.clientFields).filter(([, v]) => v);
	if (clientEntries.length > 0) {
		ensureSpace(LINE_HEIGHT * (clientEntries.length + 2));

		page.drawText('TO:', {
			x: MARGIN,
			y,
			size: 8,
			font: fontBold,
			color: GRAY,
		});
		y -= LINE_HEIGHT;

		for (const [label, value] of clientEntries) {
			page.drawText(`${label}: ${value}`, {
				x: MARGIN,
				y,
				size: 10,
				font: fontRegular,
				color: BLACK,
			});
			y -= LINE_HEIGHT;
		}
		y -= 5;
	}

	y -= 5;
	drawHR(page, y);
	y -= SECTION_GAP;

	// ── BODY TEXT ──────────────────────────────────────
	const bodyLines = wrapText(options.bodyText, fontRegular, 10, CONTENT_WIDTH);

	for (const line of bodyLines) {
		ensureSpace(LINE_HEIGHT);

		if (line === '') {
			y -= LINE_HEIGHT * 0.6;
			continue;
		}

		page.drawText(line, {
			x: MARGIN,
			y,
			size: 10,
			font: fontRegular,
			color: BLACK,
		});
		y -= LINE_HEIGHT;
	}

	// ── SIGNATURE LINES ──────────────────────────────
	y -= SECTION_GAP * 2;
	ensureSpace(80);

	drawHR(page, y);
	y -= SECTION_GAP;

	// Left signature
	page.drawLine({
		start: { x: MARGIN, y },
		end: { x: MARGIN + 200, y },
		thickness: 0.5,
		color: BLACK,
	});
	page.drawText('Signature', {
		x: MARGIN,
		y: y - 12,
		size: 8,
		font: fontRegular,
		color: GRAY,
	});
	page.drawLine({
		start: { x: MARGIN, y: y - 30 },
		end: { x: MARGIN + 200, y: y - 30 },
		thickness: 0.5,
		color: BLACK,
	});
	page.drawText('Date', {
		x: MARGIN,
		y: y - 42,
		size: 8,
		font: fontRegular,
		color: GRAY,
	});

	// Right signature
	const rightX = PAGE_WIDTH - MARGIN - 200;
	page.drawLine({
		start: { x: rightX, y },
		end: { x: rightX + 200, y },
		thickness: 0.5,
		color: BLACK,
	});
	page.drawText('Signature', {
		x: rightX,
		y: y - 12,
		size: 8,
		font: fontRegular,
		color: GRAY,
	});
	page.drawLine({
		start: { x: rightX, y: y - 30 },
		end: { x: rightX + 200, y: y - 30 },
		thickness: 0.5,
		color: BLACK,
	});
	page.drawText('Date', {
		x: rightX,
		y: y - 42,
		size: 8,
		font: fontRegular,
		color: GRAY,
	});

	// Draw page number on last page
	drawPageNumber(page, pageNum);

	return await pdfDoc.save();
}
