/** Site observation report PDF builder using pdf-lib */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const PAGE_WIDTH = 612; // US Letter
const PAGE_HEIGHT = 792;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 14;
const SECTION_GAP = 20;

const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.4, 0.4, 0.4);
const LIGHT_GRAY = rgb(0.7, 0.7, 0.7);
const ACCENT = rgb(0.29, 0.48, 0.96);

interface PhotoEntry {
	imageBytes: ArrayBuffer;
	mimeType: string;
	title: string | null;
	notes: string | null;
	aiDescription: string | null;
	createdAt: string;
}

interface ReportOptions {
	reportTitle: string;
	reportNotes: string;
	projectName: string;
	companyName: string;
	date: string;
	photos: PhotoEntry[];
}

/** Wrap text into lines that fit within maxWidth */
function wrapText(
	text: string,
	font: any,
	fontSize: number,
	maxWidth: number
): string[] {
	const lines: string[] = [];
	const paragraphs = text.split('\n');

	for (const paragraph of paragraphs) {
		if (paragraph.trim() === '') {
			lines.push('');
			continue;
		}

		const words = paragraph.split(/\s+/);
		let currentLine = '';

		for (const word of words) {
			const testLine = currentLine ? `${currentLine} ${word}` : word;
			const width = font.widthOfTextAtSize(testLine, fontSize);

			if (width > maxWidth && currentLine) {
				lines.push(currentLine);
				currentLine = word;
			} else {
				currentLine = testLine;
			}
		}

		if (currentLine) {
			lines.push(currentLine);
		}
	}

	return lines;
}

export async function buildSiteReport(options: ReportOptions): Promise<Uint8Array> {
	const pdfDoc = await PDFDocument.create();
	const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
	const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
	const fontItalic = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

	let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
	let y = PAGE_HEIGHT - MARGIN;
	let pageNum = 1;

	function ensureSpace(needed: number) {
		if (y - needed < MARGIN + 30) {
			drawPageFooter(page, pageNum);
			page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
			y = PAGE_HEIGHT - MARGIN;
			pageNum++;
		}
	}

	function drawPageFooter(pg: any, num: number) {
		const text = `Page ${num}`;
		const width = fontRegular.widthOfTextAtSize(text, 8);
		pg.drawText(text, {
			x: PAGE_WIDTH / 2 - width / 2,
			y: 25,
			size: 8,
			font: fontRegular,
			color: LIGHT_GRAY,
		});
		const footer = 'Generated by CollectRelay';
		const fWidth = fontRegular.widthOfTextAtSize(footer, 7);
		pg.drawText(footer, {
			x: PAGE_WIDTH - MARGIN - fWidth,
			y: 25,
			size: 7,
			font: fontRegular,
			color: LIGHT_GRAY,
		});
	}

	function drawHR(y: number) {
		page.drawLine({
			start: { x: MARGIN, y },
			end: { x: PAGE_WIDTH - MARGIN, y },
			thickness: 0.5,
			color: LIGHT_GRAY,
		});
	}

	// ── COVER PAGE ──────────────────────────────────────

	// Company name (right-aligned)
	const companyWidth = fontBold.widthOfTextAtSize(options.companyName, 14);
	page.drawText(options.companyName, {
		x: PAGE_WIDTH - MARGIN - companyWidth,
		y: y - 14,
		size: 14,
		font: fontBold,
		color: BLACK,
	});

	// Date (right-aligned, below company)
	const dateWidth = fontRegular.widthOfTextAtSize(options.date, 9);
	page.drawText(options.date, {
		x: PAGE_WIDTH - MARGIN - dateWidth,
		y: y - 28,
		size: 9,
		font: fontRegular,
		color: GRAY,
	});

	y -= 50 + SECTION_GAP;

	// Title
	drawHR(y);
	y -= SECTION_GAP;

	const titleLines = wrapText(options.reportTitle, fontBold, 20, CONTENT_WIDTH);
	for (const line of titleLines) {
		const tw = fontBold.widthOfTextAtSize(line, 20);
		page.drawText(line, {
			x: PAGE_WIDTH / 2 - tw / 2,
			y,
			size: 20,
			font: fontBold,
			color: ACCENT,
		});
		y -= 26;
	}

	y -= 5;
	drawHR(y);
	y -= SECTION_GAP;

	// "Site Observation Report" subtitle
	const subtitle = 'Site Observation Report';
	const subtitleWidth = fontRegular.widthOfTextAtSize(subtitle, 12);
	page.drawText(subtitle, {
		x: PAGE_WIDTH / 2 - subtitleWidth / 2,
		y,
		size: 12,
		font: fontRegular,
		color: GRAY,
	});
	y -= SECTION_GAP;

	// Project name
	page.drawText('Project:', {
		x: MARGIN,
		y,
		size: 10,
		font: fontBold,
		color: GRAY,
	});
	page.drawText(options.projectName, {
		x: MARGIN + 50,
		y,
		size: 10,
		font: fontRegular,
		color: BLACK,
	});
	y -= LINE_HEIGHT;

	// Photo count
	page.drawText('Photos:', {
		x: MARGIN,
		y,
		size: 10,
		font: fontBold,
		color: GRAY,
	});
	page.drawText(`${options.photos.length}`, {
		x: MARGIN + 50,
		y,
		size: 10,
		font: fontRegular,
		color: BLACK,
	});
	y -= LINE_HEIGHT * 2;

	// Report notes
	if (options.reportNotes) {
		page.drawText('Notes:', {
			x: MARGIN,
			y,
			size: 10,
			font: fontBold,
			color: GRAY,
		});
		y -= LINE_HEIGHT;

		const noteLines = wrapText(options.reportNotes, fontRegular, 10, CONTENT_WIDTH);
		for (const line of noteLines) {
			ensureSpace(LINE_HEIGHT);
			if (line === '') {
				y -= LINE_HEIGHT * 0.6;
				continue;
			}
			page.drawText(line, {
				x: MARGIN,
				y,
				size: 10,
				font: fontRegular,
				color: BLACK,
			});
			y -= LINE_HEIGHT;
		}
	}

	drawPageFooter(page, pageNum);

	// ── PHOTO PAGES ──────────────────────────────────────

	for (let i = 0; i < options.photos.length; i++) {
		const photo = options.photos[i];

		// Start new page for each photo
		page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
		y = PAGE_HEIGHT - MARGIN;
		pageNum++;

		// Photo header
		const photoLabel = `Photo ${i + 1} of ${options.photos.length}`;
		page.drawText(photoLabel, {
			x: MARGIN,
			y,
			size: 9,
			font: fontRegular,
			color: GRAY,
		});

		// Date on right
		if (photo.createdAt) {
			const dateStr = new Date(photo.createdAt + 'Z').toLocaleDateString('en-US', {
				month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit'
			});
			const dw = fontRegular.widthOfTextAtSize(dateStr, 9);
			page.drawText(dateStr, {
				x: PAGE_WIDTH - MARGIN - dw,
				y,
				size: 9,
				font: fontRegular,
				color: GRAY,
			});
		}

		y -= 5;
		drawHR(y);
		y -= SECTION_GAP;

		// Title
		if (photo.title) {
			const titleText = photo.title;
			page.drawText(titleText, {
				x: MARGIN,
				y,
				size: 14,
				font: fontBold,
				color: BLACK,
			});
			y -= 20;
		}

		// Embed the image
		try {
			let image;
			if (photo.mimeType.includes('png')) {
				image = await pdfDoc.embedPng(photo.imageBytes);
			} else {
				// JPEG and WebP (WebP may not be supported, fallback gracefully)
				image = await pdfDoc.embedJpg(photo.imageBytes);
			}

			if (image) {
				// Scale image to fit content width, max height 350
				const maxImgWidth = CONTENT_WIDTH;
				const maxImgHeight = 350;
				const scale = Math.min(
					maxImgWidth / image.width,
					maxImgHeight / image.height,
					1
				);
				const drawWidth = image.width * scale;
				const drawHeight = image.height * scale;

				// Check if we have enough space
				if (y - drawHeight < MARGIN + 100) {
					// Image won't fit with room for text below — scale down further
					const availableHeight = y - MARGIN - 150;
					if (availableHeight > 100) {
						const fitScale = Math.min(scale, availableHeight / image.height);
						const fitWidth = image.width * fitScale;
						const fitHeight = image.height * fitScale;

						page.drawImage(image, {
							x: MARGIN + (CONTENT_WIDTH - fitWidth) / 2,
							y: y - fitHeight,
							width: fitWidth,
							height: fitHeight,
						});
						y -= fitHeight + 15;
					}
				} else {
					page.drawImage(image, {
						x: MARGIN + (CONTENT_WIDTH - drawWidth) / 2,
						y: y - drawHeight,
						width: drawWidth,
						height: drawHeight,
					});
					y -= drawHeight + 15;
				}
			}
		} catch (err) {
			// If image embed fails, note it
			page.drawText('[Image could not be embedded]', {
				x: MARGIN,
				y,
				size: 10,
				font: fontItalic,
				color: GRAY,
			});
			y -= LINE_HEIGHT;
		}

		// Notes
		if (photo.notes) {
			ensureSpace(LINE_HEIGHT * 3);
			page.drawText('Notes:', {
				x: MARGIN,
				y,
				size: 9,
				font: fontBold,
				color: GRAY,
			});
			y -= LINE_HEIGHT;

			const noteLines = wrapText(photo.notes, fontRegular, 10, CONTENT_WIDTH);
			for (const line of noteLines) {
				ensureSpace(LINE_HEIGHT);
				if (line === '') {
					y -= LINE_HEIGHT * 0.6;
					continue;
				}
				page.drawText(line, {
					x: MARGIN,
					y,
					size: 10,
					font: fontRegular,
					color: BLACK,
				});
				y -= LINE_HEIGHT;
			}
			y -= 5;
		}

		// AI Description
		if (photo.aiDescription) {
			ensureSpace(LINE_HEIGHT * 3);
			page.drawText('AI Analysis:', {
				x: MARGIN,
				y,
				size: 9,
				font: fontBold,
				color: ACCENT,
			});
			y -= LINE_HEIGHT;

			const descLines = wrapText(photo.aiDescription, fontItalic, 9, CONTENT_WIDTH);
			for (const line of descLines) {
				ensureSpace(LINE_HEIGHT);
				if (line === '') {
					y -= LINE_HEIGHT * 0.6;
					continue;
				}
				page.drawText(line, {
					x: MARGIN,
					y,
					size: 9,
					font: fontItalic,
					color: GRAY,
				});
				y -= LINE_HEIGHT - 2;
			}
		}

		drawPageFooter(page, pageNum);
	}

	return await pdfDoc.save();
}
